version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    ports:
      - 5432:${db_port}

    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:${adminer_port}



      